# Methos Linux - mkinitcpio Configuration
# This file is used by mkarchiso to generate the initramfs

MODULES=()

BINARIES=()

FILES=()

HOOKS=(base udev autodetect modconf intel-ucode block filesystems keyboard fsck)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-1)