# Methos Linux UEFI boot entry
title   Methos Linux
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/intel-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisodevice=LABEL=METHOS archisoboot=live cow_spacesize=4G quiet